all:

scheme-full:
	@docker build --build-arg SCHEME=scheme-full ngoquangduong/texlive:scheme-full .
medium:
	@docker build --build-arg SCHEME=medium ngoquangduong/texlive:medium .
small:
	@docker build --build-arg SCHEME=small ngoquangduong/texlive:small .
basic:
	@docker build --build-arg SCHEME=basic ngoquangduong/texlive:basic .
minimal:
	@docker build --build-arg SCHEME=minimal ngoquangduong/texlive:minimal .
context:
	@docker build --build-arg SCHEME=context ngoquangduong/texlive:content .
gust:
	@docker build --build-arg SCHEME=gust ngoquangduong/texlive:gust .
infraonly:
	@docker build --build-arg SCHEME=infraonly ngoquangduong/texlive:infraonly .
tetex:
	@docker build --build-arg SCHEME=tetex ngoquangduong/texlive:tetex .

