name: "Docker images for TeX Live"

on:
  push:
    branches:
      - master

jobs:
  texlive-infraonly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Build image"
        run: cd texlive && docker build --build-arg SCHEME=infraonly ngoquangduong/texlive:infraonly .
      - name: "Publish image to Docker Hub"
        env:
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo $DOCKER_HUB_ACCESS_TOKEN | docker login --username ngoquangduong --password-stdin
          docker push ngoquangduong/texlive:infraonly
