name: "Docker image for TeX Live: teTeX (more than medium, but nowhere near full)"

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/texlive-tetex.yml
      - texlive/**
  schedule:
    - cron: "0 0 27 * *"

jobs:
  texlive-tetex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Build image"
        run: cd texlive && docker build --build-arg SCHEME=tetex --tag ngoquangduong/texlive:tetex .
      - name: "Publish image to Docker Hub"
        env:
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo $DOCKER_HUB_ACCESS_TOKEN | docker login --username ngoquangduong --password-stdin
          docker push ngoquangduong/texlive:tetex
          rm ~/.docker/config.json
