name: "Docker images for TeX Live: basic (plain and latex)"

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/texlive-basic.yml
      - texlive/**
  schedule:
    - cron: "0 0 1 * *"

jobs:
  texlive-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Build image"
        run: cd texlive && docker build --build-arg SCHEME=basic --tag ngoquangduong/texlive:basic .
      - name: "Publish image to Docker Hub"
        env:
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo $DOCKER_HUB_ACCESS_TOKEN | docker login --username ngoquangduong --password-stdin
          docker push ngoquangduong/texlive:basic
